# Generated by Django 4.2.13 on 2024-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demarches_simplifiees", "0002_alter_dsfolder_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dsfolder",
            name="dossier_prefill_token",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="dsfolder",
            name="state",
            field=models.CharField(max_length=255),
        ),
    ]
